# Generated by Django 5.0.4 on 2024-04-24 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='author_ebooks', to='ebooks.author'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ebooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='genre_ebooks', to='ebooks.genre'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='num_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
